name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        git submodule update --init
        docker build . --file Dockerfile --tag aspushedp/neovim:arm64 --platform linux/arm64
        docker build . --file Dockerfile --tag aspushedp/neovim:amd64 --platform linux/amd64
